/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEWS;

import DAO.Usuario_DAO;
import DTO.Usuario;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.util.Date;

/**
 *
 * @author Intel i5
 */
public class Janela_cadastro extends javax.swing.JFrame {
    private Usuario usuario;
    /**
     * Creates new form Janela_cadastro
     */
    public Janela_cadastro(Usuario u) {
        initComponents();
        
        this.usuario = u;
        
        if(u != null){
            
            int sxo;
            
            switch (u.getSexo()) {
                case "M":
                    sxo = 1;
                    break;
                case "F":
                    sxo = 2;
                    break;
                default:
                    sxo = 0;
            }
            
            txtUSUARIO.setText(u.getUsua());
            txtSENHA.setText(u.getSenha());
            txtNOME.setText(u.getNome());
            txtIDADE.setText(String.valueOf(u.getIdade()));
            cmbSEXO.setSelectedIndex(sxo);
            txtEMAIL.setText(u.getEmail());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtSENHA = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNOME = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtIDADE = new javax.swing.JTextField();
        txtUSUARIO = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtEMAIL = new javax.swing.JTextField();
        cmbSEXO = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        pnlINCORRETO = new javax.swing.JPanel();
        lblINCORRETO = new javax.swing.JLabel();
        btnSALVAR = new javax.swing.JButton();
        btnCANCELAR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel3.setText("Nome:");

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel1.setText("Usuário:");

        jLabel6.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel6.setText("Idade:");

        jLabel7.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel7.setText("E-mail:");

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel2.setText("Senha:");

        txtEMAIL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEMAILActionPerformed(evt);
            }
        });

        cmbSEXO.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Não Informar", "Masculino", "Feminino" }));
        cmbSEXO.setBorder(null);
        cmbSEXO.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cmbSEXO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSEXOActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel4.setText("Sexo:");

        pnlINCORRETO.setBackground(new java.awt.Color(153, 153, 153));
        pnlINCORRETO.setForeground(new java.awt.Color(204, 204, 0));

        lblINCORRETO.setBackground(new java.awt.Color(153, 153, 153));
        lblINCORRETO.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        lblINCORRETO.setForeground(new java.awt.Color(255, 0, 0));
        lblINCORRETO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnlINCORRETOLayout = new javax.swing.GroupLayout(pnlINCORRETO);
        pnlINCORRETO.setLayout(pnlINCORRETOLayout);
        pnlINCORRETOLayout.setHorizontalGroup(
            pnlINCORRETOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlINCORRETOLayout.createSequentialGroup()
                .addComponent(lblINCORRETO, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        pnlINCORRETOLayout.setVerticalGroup(
            pnlINCORRETOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblINCORRETO, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSENHA, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUSUARIO, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtIDADE, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNOME, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(144, 144, 144)
                        .addComponent(cmbSEXO, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(pnlINCORRETO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtEMAIL, txtIDADE});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtNOME, txtSENHA, txtUSUARIO});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel4, jLabel6, jLabel7});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUSUARIO, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIDADE, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSENHA, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel2))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbSEXO, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtNOME, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(pnlINCORRETO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtEMAIL, txtIDADE});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtNOME, txtSENHA, txtUSUARIO});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel4, jLabel6, jLabel7});

        btnSALVAR.setText("Salvar");
        btnSALVAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSALVARActionPerformed(evt);
            }
        });

        btnCANCELAR.setText("Cancelar");
        btnCANCELAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCANCELARActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSALVAR, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(134, 134, 134)
                .addComponent(btnCANCELAR, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSALVAR, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCANCELAR, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnCANCELAR, btnSALVAR});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbSEXOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSEXOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbSEXOActionPerformed

    private void txtEMAILActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEMAILActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEMAILActionPerformed

    private void btnCANCELARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCANCELARActionPerformed
      dispose(); 
      if(this.usuario == null){
            new Janela_login().setVisible(true);
       }else{
           new Janela_principal(this.usuario).setVisible(true);
       }
    }//GEN-LAST:event_btnCANCELARActionPerformed

    private void btnSALVARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSALVARActionPerformed
       
        if(this.usuario == null){
           cadastrar();
           
       }else{  
            Usuario_DAO dao = new Usuario_DAO();
            
               String sxo;
                int item = cmbSEXO.getSelectedIndex();
                
                switch(item){
                    case 1:
                        sxo = "M";
                        break;
                    case 2:
                        sxo = "F";
                        break;
                    default:
                        sxo = "Não informado";
                }
                
            
            this.usuario.setUsua(txtUSUARIO.getText().trim());
            this.usuario.setSenha(txtSENHA.getText().trim());
            this.usuario.setNome(txtNOME.getText());
            this.usuario.setIdade(Integer.parseInt(txtIDADE.getText().trim()));
            this.usuario.setSexo(sxo);
            this.usuario.setDatacadastro(new Date());
            this.usuario.setEmail(txtEMAIL.getText().trim());
            
           int opc = JOptionPane.showConfirmDialog(null, "Você deseja realmente editar seus dados?", "Aviso", 0, 3);
           
           if(opc == 0){
                dao.AtualizarUsuario(this.usuario);
                dispose();
                new Janela_principal(this.usuario).setVisible(true);
           }

           }
    }//GEN-LAST:event_btnSALVARActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Janela_cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Janela_cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Janela_cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Janela_cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Janela_cadastro(null).setVisible(true);
            }
        });
    }
    
    public void cadastrar(){
        
        Usuario_DAO dao = new Usuario_DAO();
      
        
        try {
            
            ResultSet rs = dao.autenticaUsuarioEmail(txtUSUARIO.getText().trim(), txtEMAIL.getText().trim());
            
            if(rs.next()){
                
                pnlINCORRETO.setBackground(new java.awt.Color(255, 240, 110));
                pnlINCORRETO.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                pnlINCORRETO.setForeground(new java.awt.Color(204, 204, 0));
                lblINCORRETO.setText("Usuário ou e-mail já existem.");
            
            }else if(txtUSUARIO.getText().trim().equals("") || txtSENHA.getText().trim().equals("") || txtEMAIL.getText().trim().equals("") || txtIDADE.getText().trim().equals("") || txtNOME.getText().trim().equals("")){
                
                pnlINCORRETO.setBackground(new java.awt.Color(255, 240, 110));
                pnlINCORRETO.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
                pnlINCORRETO.setForeground(new java.awt.Color(204, 204, 0));
                lblINCORRETO.setText("Alguns dos campos não foram preenchidos.");
            }else{
                
                String sxo;
                int item = cmbSEXO.getSelectedIndex();
                
                switch(item){
                    case 1:
                        sxo = "M";
                        break;
                    case 2:
                        sxo = "F";
                        break;
                    default:
                        sxo = "Não informado";
                }
                
                
                Usuario usuario = new Usuario();
                
                usuario.setUsua(txtUSUARIO.getText().trim());
                usuario.setSenha(txtSENHA.getText().trim());
                usuario.setNome(txtNOME.getText());
                usuario.setIdade(Integer.parseInt(txtIDADE.getText().trim()));
                usuario.setSexo(sxo);
                usuario.setDatacadastro(new Date());
                usuario.setEmail(txtEMAIL.getText().trim());
                
                dao.InserirUsuario(usuario);
                
                dispose();
                JOptionPane.showMessageDialog(null, "Novo usuário criado com sucesso, faça login para prosseguir.");
                 
                new Janela_login().setVisible(true);
            }
            
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "cadastrar: " + erro.getMessage());
            
        }finally{
            dao.FecharConexao();       
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCANCELAR;
    private javax.swing.JButton btnSALVAR;
    private javax.swing.JComboBox<String> cmbSEXO;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblINCORRETO;
    private javax.swing.JPanel pnlINCORRETO;
    private javax.swing.JTextField txtEMAIL;
    private javax.swing.JTextField txtIDADE;
    private javax.swing.JTextField txtNOME;
    private javax.swing.JTextField txtSENHA;
    private javax.swing.JTextField txtUSUARIO;
    // End of variables declaration//GEN-END:variables
}
